---
title: "hierarchical clustering_RNA"
output: html_notebook
---

```{r}

#read rna count_matrix
rna <- read.table(
  '/home/melika/analysis/GSE159699_summary_count.star.txt', 
  header = TRUE, 
  sep = '\t',
  row.names = 'refGene' 
)
head(rna)

#read metafile
metafile <- read.csv(
  '/home/melika/analysis/star_col.csv',
  row.names = 1,
  sep = ';'
)
head(metafile)


i <- 1
for (name in colnames(rna)){
  colnames(rna)[colnames(rna) == name] <- rownames(metafile)[i]
  i = i + 1
}

# check form of data
all(rownames(metafile) %in% colnames(rna))
all(rownames(metafile) == colnames(rna))

metafile$group <- factor(metafile$group)
```

```{r}
library(DESeq2)
#create DESeq matrix
deseq_matrix <- DESeqDataSetFromMatrix(
  countData = rna,
  colData = metafile,
  design = ~ group
)

#filtering genes based on Cook's distance when there are many degrees of freedom and create DESeq object 
deseq_matrix <- DESeq(deseq_matrix)

# normalization of deseq_matrix
norm_matrix <- vst(dds_star)

#extract normalized counts in readable format from the DEseq object 
data <- assay(norm_matrix)
# save a table with the normalized data
write.table(data, sep="\t",file="Norm_data_rna.txt", row.names=TRUE,col.names=NA,quote=FALSE)

```

```{r}
#creat distance matrix 
sampleDists <- dist(t(data),  method = "euclidean")

#perform hierarchical clustering based on the distances matrix of RNA
library(rafalib)
rna_clu <- hclust(sampleDists)

#plot Dendrogram which shows the hierarchical clustering of RNA-seq
plot(rna_clu,labels=metafile$group,cex=0.5)

#add color to the cluters
myplclust(rna_clu, labels=metafile$group, lab.col=as.fumeric(as.vector(metafile$group)),cex=0.5)
```


```{r}
#cut the tree into clusters, 
#we can examine how the clusters overlap with our sample
hcluster <- cutree(rna_clu, h=30)
table(true=metafile$group, cluster=hcluster)

```

```{r}

#heatmap
library(RColorBrewer) 
library(genefilter)

hmcol <- colorRampPalette(brewer.pal(7,"YlOrBr"))(100)

rv <- rowVars(data)
#pick all the samples
idx <- order(-rv)[1:30]

library(gplots) ##Available from CRAN
head(cbind(colnames(data),cols))
cols <- palette(brewer.pal(8,"Dark2"))[as.fumeric(as.vector(metafile$group))]
heatmap.2(data[idx,], labCol=metafile$group,
          trace="none", 
          ColSideColors=cols, 
          col=hmcol)

```