---
title: "SVM Model"
output: html_notebook
---

##first tried svm methode for RNA

```{r}

#read rna count_matrix
rna_seq <- read.table(
  '/home/melika/analysis/GSE159699_summary_count.star.txt', 
  header = TRUE, 
  sep = '\t',
  row.names = 'refGene'
)
#head(rna_seq)

#read metafile
metafile<- read.csv(
  '/home/melika/analysis/star_col.csv',
  row.names = 1,
  sep = ';'
)
#head(metafile)
```

```{r}

library(DESeq2)
library(RandPro)
library(caret)
library(rlang)
set.seed(2128)


i <- 1
for (name in colnames(rna_seq)){
  colnames(rna_seq)[colnames(rna_seq) == name] <- rownames(metafile)[i]
  i = i + 1
}

# check form of data
all(rownames(metafile) %in% colnames(rna_seq))
all(rownames(metafile) == colnames(rna_seq))

metafile$group <- factor(metafile$group)

#create DESeq matrix
de_matrix <- DESeqDataSetFromMatrix(
  countData = rna_seq,
  colData = metafile,
  design = ~ group
)

#if count<10 left out that row
keep <- rowSums(counts(de_matrix)) >= 10
de_matrix <- de_matrix[keep,]

#filtering genes based on Cook's distance when there are many degrees of freedom and create DESeq object 
de_matrix <- DESeq(de_matrix)

#sorts the values of matrix given by their index in increasing order
select <- order(rowMeans(
  counts(de_matrix, normalized=TRUE)),
  decreasing=TRUE
)[1:30]

# normalization of deseq_matrix
vst <- vst(de_matrix, blind=FALSE)
#extract normalized counts in readable format from the DEseq object 
data <- assay(vst)[select,]

#splitting data
nTest <- ceiling(ncol(data) * 0.7)
ind <- sample(ncol(data), nTest, FALSE)

```


```{r}
#classification models.
train <- data[ ,ind] + 1
test <- data[ ,-ind] + 1
```

```{r}

##did not work!!!


## Support vector machines with radial basis function kernel


set.seed(2128)

svm <- classify(train,test,method = "svmRadial",preProcessing = "deseq-vst")
show(svm)
trained(svm)
plot(svm)


```


